Algoritmo "Apostila-pag76-exe4"
// Disciplina  : Linguagem e lógica de Programação
// Professor   : Ivan Paulino
// Descrição   : Hoje estamos usando o VISUALG 3.0 pela primeira vez
// Autor(a)    : João Vitor
// Data atual  : 07/08/2024
Var
numero:inteiro
Inicio

escreval ()
escreval ("OS NUMEROS ALEATORIOS GERADOS SÃO:")
escreval ()
escreval ("15")
escreval ("100")
escreval ("48")
escreval ("2")
escreval ("0")
escreval ()

Fimalgoritmo