Algoritmo "Tema 1-Página 16-Exe10"
// Disciplina  : Fundamentos da programação
// Professor   : Ivan Paulino
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : João Vitor
// Data atual  : 25/06/2024
Var
// Seção de Declarações das variáveis 
jip01, pij02 : inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Deus Ajuda quem cedo madruga")
leia (jip01)
leia (pij02)

Fimalgoritmo